fullnameOverride: opentelemetry-collector
agentCollector:
  enabled: false
standaloneCollector:
  enabled: true
  resources:
    limits:
      cpu: 64m
      memory: 128Mi
  configOverride:
    exporters:
      otlp/elastic:
        endpoint: 192.168.137.1:8200
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp/elastic
        traces:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp/elastic