apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
      compoment: java
  template:
    metadata:
      labels:
        app: order-service
        compoment: java
    spec:
      initContainers:
        - name: otel-javaagent
          image: ebinsu/agent:1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: otel-javaagent
              mountPath: /otel-javaagent
      containers:
        - image: ebinsu/order-service:27
          imagePullPolicy: IfNotPresent
          name: order-service
          env:
            - name: JAVA_OPTS
              value: "-javaagent:/otel-javaagent/opentelemetry-javaagent.jar"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://opentelemetry-collector:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=order-service,service.namespace=defalut"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: otel-javaagent
              mountPath: /otel-javaagent
      volumes:
        - emptyDir: { }
          name: otel-javaagent
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  ports:
    - name: port
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
  selector:
    app: order-service
    compoment: java

