persistence:
  enabled: true
config:
  table_manager:
    retention_deletes_enabled: true
    retention_period: 24h
  ruler:
    storage:
      type: local
      local:
        directory: /rules
    rule_path: /tmp/scratch
    alertmanager_url: http://prometheus-alertmanager
    ring:
      kvstore:
        store: inmemory
    enable_api: true

alerting_groups:
  - name: should_fire
    rules:
      - alert: logging-error
        expr: |
          sum by (app) (rate({component="java",level="ERROR"}[1m])) > 0
        labels:
          severity: red
        annotations:
          summary: "{{ $labels.namespace }} {{ $labels.pod }}java logging error"

service:
  type: NodePort
  nodePort: 30101