#  regex see： https://regoio.herokuapp.com/
fullnameOverride: promtail
config:
  lokiAddress: http://loki:3100/loki/api/v1/push
  snippets:
    pipelineStages:
      - docker: { }
      - labeldrop:
          - container
          - job
      - match:
          selector: '{component="java"}'
          stages:
            - multiline:
                firstline: ^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}
            - regex:
                expression: \d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\s(?P<trace_id>[0-9a-z]{32})?\s(?P<span_id>[0-9a-z]{16})?\s(?P<level>\w{4,5})(?:.|\n)*
            - replace:
                expression: "(\\n)"
                replace: ""
            - labeldrop:
                - stream
            - labels:
                level:
                trace_id:
                span_id:
